const adjectives = [
    'retro', 
    'baffling',
    'passe',
    'old time',
    'evocative',
    'old',
    'old fashioned',
    '80s',
    '90s',
    '70s',
    'garbage',
    'ancient',
    'nostalgic',
    'powerful',
    'dumb',
    'stupid',
    'tiny',
    'huge',
    'gold',
    'huge gold',
    'antique',
    'pristine',
    'new in box',
    'outrageous',
    'nu metal',
    'regretful',
    'cornball',
    'wistful',
    'bussin',
    'anime',
    'chic',
    'acute',
    'aquatic',
    'subterainian',
    'small town',
    'youthful'
];

const nouns = [
    'skelton', 
    'shrimp',
    'donkey',
    'playstation',
    'chair',
    'gundam model',
    'noodles',
    'vhs',
    'model',
    'toy',
    'board game',
    'rooster',
    'shark toy',
    'chips',
    'soda',
    'candy',
    'arbys',
    'clown',
    'video game',
    'movie',
    'treasure',
    'glove',
    'tiger toy',
    'ape',
    'house',
    'car',
    'trailer',
    'radio',
    'music',
    'cd',
    'record',
    '8 track',
    'mannequin',
    'dude',
    'skateboard',
    'console',
    'computer',
    'school',
    'monster',
    'alien',
    'gun',
    'food product',
    'knock off pokemon',
    'circus',
    'dragonball',
    'blanket',
    'costume',
    'video store',
    'gas station'
];

const searchTerm = () => {
    const randomAdjective = adjectives[Math.floor(Math.random() * adjectives.length)];
    const randomNoun = nouns[Math.floor(Math.random() * nouns.length)];
    return `${randomAdjective} ${randomNoun}`
}

module.exports = searchTerm