const adjectives = [
  'retro',
  'baffling',
  'passe',
  'old time',
  'evocative',
  'old',
  'old fashioned',
  '80s',
  '90s',
  '70s',
  'garbage',
  'ancient',
  'nostalgic',
  'powerful',
  'dumb',
  'stupid',
  'tiny',
  'huge',
  'gold',
  'huge gold',
  'antique',
  'pristine',
  'new in box',
  'outrageous',
  'nu metal',
  'regretful',
  'cornball',
  'wistful',
  'anime',
  'chic',
  'acute',
  'aquatic',
  'subterainian',
  'small town',
  'youthful',
  'wicker',
  'ai generated',
  'homemade',
  'diy',
  'churlish',

];

const nouns = [
  'skeleton',
  'shrimp',
  'donkey',
  'playstation',
  'chair',
  'gundam model',
  'noodles',
  'vhs',
  'model',
  'toy',
  'board game',
  'shark toy',
  'chips',
  'soda',
  'candy',
  'arbys',
  'clown',
  'video game',
  'movie',
  'treasure',
  'glove',
  'tiger toy',
  'ape',
  'house',
  'car',
  'trailer',
  'radio',
  'music',
  'cd',
  'record',
  '8 track',
  'mannequin',
  'dude',
  'skateboard',
  'console',
  'computer',
  'school',
  'monster',
  'alien',
  'gun',
  'food product',
  'knock off pokemon',
  'circus',
  'dragonball',
  'blanket',
  'costume',
  'video store',
  'gas station',
  'dinner ware',
  'animal',
  'apartment',
  'rug',
  'bed linen',
  'art',
  'ball',
  'toilet',
  'bathroom',
  'beer',
  'speed boat',
  'camera',
  'cigarettes',
  'company',
  'bike',
  'motorcycle',
  'dinner',
  'disk',
  'gift',
  'grocery store',
  'phone',
  'restaurant',
  'snack',
  'sign',
  'shirt',
  'clothes',
  'haircut'
];

const countries = [
  "Afghan",  "Albanian",  "Algerian",  "American",  "Andorran",  "Angolan",  "Antiguans",
  "Argentinean",
  "Armenian",
  "Australian",
  "Austrian",
  "Azerbaijani",
  "Bahamian",
  "Bahraini",
  "Bangladeshi",
  "Barbadian",
  "Barbudans",
  "Batswana",
  "Belarusian",
  "Belgian",
  "Belizean",
  "Beninese",
  "Bhutanese",
  "Bolivian",
  "Bosnian",
  "Brazilian",
  "British",
  "Bruneian",
  "Bulgarian",
  "Burkinabe",
  "Burmese",
  "Burundian",
  "Cambodian",
  "Cameroonian",
  "Canadian",
  "Cape Verdean",
  "Central African",
  "Chadian",
  "Chilean",
  "Chinese",
  "Colombian",
  "Comoran",
  "Congolese",
  "Costa Rican",
  "Croatian",
  "Cuban",
  "Cypriot",
  "Czech",
  "Danish",
  "Djibouti",
  "Dominican",
  "Dutch",
  "East Timorese",
  "Ecuadorean",
  "Egyptian",
  "Emirian",
  "Equatorial Guinean",
  "Eritrean",
  "Estonian",
  "Ethiopian",
  "Fijian",
  "Filipino",
  "Finnish",
  "French",
  "Gabonese",
  "Gambian",
  "Georgian",
  "German",
  "Ghanaian",
  "Greek",
  "Grenadian",
  "Guatemalan",
  "Guinea-Bissauan",
  "Guinean",
  "Guyanese",
  "Haitian",
  "Herzegovinian",
  "Honduran",
  "Hungarian",
  "I-Kiribati",
  "Icelander",
  "Indian",
  "Indonesian",
  "Iranian",
  "Iraqi",
  "Irish",
  "Israeli",
  "Italian",
  "Ivorian",
  "Jamaican",
  "Japanese",
  "Jordanian",
  "Kazakhstani",
  "Kenyan",
  "Kittian and Nevisian",
  "Kuwaiti",
  "Kyrgyz",
  "Laotian",
  "Latvian",
  "Lebanese",
  "Liberian",
  "Libyan",
  "Liechtensteiner",
  "Lithuanian",
  "Luxembourger",
  "Macedonian",
  "Malagasy",
  "Malawian",
  "Malaysian",
  "Maldivian",
  "Malian",
  "Maltese",
  "Marshallese",
  "Mauritanian",
  "Mauritian",
  "Mexican",
  "Micronesian",
  "Moldovan",
  "Monacan",
  "Mongolian",
  "Moroccan",
  "Mosotho",
  "Motswana",
  "Mozambican",
  "Namibian",
  "Nauruan",
  "Nepalese",
  "New Zealander",
  "Ni-Vanuatu",
  "Nicaraguan",
  "Nigerian",
  "Nigerien",
  "North Korean",
  "Northern Irish",
  "Norwegian",
  "Omani",
  "Pakistani",
  "Palauan",
  "Panamanian",
  "Papua New Guinean",
  "Paraguayan",
  "Peruvian",
  "Polish",
  "Portuguese",
  "Qatari",
  "Romanian",
  "Russian",
  "Rwandan",
  "Saint Lucian",
  "Salvadoran",
  "Samoan",
  "San Marinese",
  "Sao Tomean",
  "Saudi",
  "Scottish",
  "Senegalese",
  "Serbian",
  "Seychellois",
  "Sierra Leonean",
  "Singaporean",
  "Slovakian",
  "Slovenian",
  "Solomon Islander",
  "Somali",
  "South African",
  "South Korean",
  "Spanish",
  "Sri Lankan",
  "Sudanese",
  "Surinamer",
  "Swazi",
  "Swedish",
  "Swiss",
  "Syrian",
  "Taiwanese",
  "Tajik",
  "Tanzanian",
  "Thai",
  "Togolese",
  "Tongan",
  "Trinidadian or Tobagonian",
  "Tunisian",
  "Turkish",
  "Tuvaluan",
  "Ugandan",
  "Ukrainian",
  "Uruguayan",
  "Uzbekistani",
  "Venezuelan",
  "Vietnamese",
  "Welsh",
  "Yemenite",
  "Zambian",
  "Zimbabwean"
];

const randomItem = (list) => {
  return list[Math.floor(Math.random() * list.length)];
}

const searchTerm = () => {
  const countryDecider = Math.floor(Math.random() * (10 - 1 + 1) + 1);
  const randomAdjective = randomItem(adjectives);
  const randomNoun = randomItem(nouns);
  const randomCountryOrSpace = countryDecider === 10 ? ` ${randomItem(countries)} ` : ' '
  const searchTerm = `${randomAdjective}${randomCountryOrSpace}${randomNoun}`;
  
  console.log(`Searching for an image of ${searchTerm}`);
  
  return searchTerm;
};

module.exports = searchTerm;
